### ISSUE TITLE
How to handle exposure with patsy a.ka. offset function

### ISSUE THREAD

**Issue by olivier-lacroix** [pydata/patsy#101]
Hi,

I am considering using pymc3 for a Poisson GLM application, and am looking for a way to take into account an exposure parameter.

In R, this can be indicated via an offset function, basically indicating that regression parameter shall be 1. see for instance https://stat.ethz.ch/R-manual/R-devel/library/stats/html/offset.html

I have not found a straightforward way to this with patsy. Have I missed something? Is this doable in patsy?

Thank you,

Olivier

**Comment by njsmith** [comment]
There isn't currently any way to support the R style glm("y ~ x +
offset(z)") syntax in Patsy; the parser doesn't have syntax for this kind
of magic function. But even if this were possible at the Patsy level, all
it would do is give a way to pass through the offset value to the
underlying model code, which have to have code written to support offsets.
I'd suggest using a kwarg instead, like: glm("y ~ x", offset=z) or similar.
I don't know whether pymc3 supports anything like this; you'll have to ask
them.

**Comment by olivier-lacroix** [comment]
Fair enough, thank you very much for your fast answer
