### ISSUE TITLE
Polynomial contrast coding

### ISSUE THREAD

**Issue by jingw222** [pydata/patsy#106]
Is there a way to employ polynomial contrast coding `patsy.Poly` on,  say, a categorical variable of four levels that is only up to quadratic level instead of cubic one?

**Comment by njsmith** [comment]
There's nothing built-in, but you can [use an arbitrary contrast matrix or define your own coding scheme](https://patsy.readthedocs.io/en/latest/categorical-coding.html). The former just involves passing a matrix with your desired coding to `C(...)` (there are examples in that link); the latter would look something like (untested but hopefully gives the idea):
```python
class Quadratic(object):
    def code_with_intercept(self, levels):
        cm = patsy.Poly().code_with_intercept(levels)
        # with_intercept coding has 0th, 1st, 2nd order terms = 3 terms total
        return patsy.ContrastMatrix(cm.matrix[:, :3], cm.column_suffixes[:3])

    def code_without_intercept(self, levels):
        cm = patsy.Poly().code_without_intercept(levels)
        # without_intercept coding has 1st & 2nd order terms = 2 terms total
        return patsy.ContrastMatrix(cm.matrix[:, :2], cm.column_suffixes[:2])

dmatrix("y ~ C(a, Quadratic)")
```
