### ISSUE TITLE
Unquote Q(' ')

### ISSUE THREAD

**Issue by saroele** [pydata/patsy#113]
I'm constructing formulas from pandas DataFrames that users pass as input. To escape all kind of strange characters in the column names, I'm quoting each column with `Q('column_name')`.

When I pass the resulting formulas to statsmodels OLS and print a summary, all my variables are shown as `Q('column_name')`.  Can I unquote these variables somehow?

**Comment by njsmith** [comment]
If you're constructing formulas programmatically, have you considered using [`LookupFactor`](https://patsy.readthedocs.io/en/latest/API-reference.html#patsy.LookupFactor)? There's an example here: https://stackoverflow.com/questions/38149482/using-ols-function-with-parameters-that-contain-numbers-spaces/38167185#38167185

**Comment by saroele** [comment]
Thanks for the link, looks exactly like what I need.

**Comment by njsmith** [comment]
Excellent.
