### ISSUE TITLE
RLS: patsy 0.5.0

### ISSUE THREAD

**Issue by jreback** [pydata/patsy#115]
pandas is removing this deprecation of dtype instrospection functions that were originally defined in ``pandas.core.common``, these are now in ``pandas.api.types``.  It seems that the code to fix this is already in master (of patsy), just needs a release to push out. last release was late 2015.

**Comment by jreback** [comment]
xref https://github.com/pandas-dev/pandas/pull/13147

**Comment by jreback** [comment]
ping @njsmith

**Comment by njsmith** [comment]
Patsy 0.5.0 is on pypi.

**Comment by jreback** [comment]
thanks @njsmith 

I also put up: https://github.com/conda-forge/patsy-feedstock/pull/7
