### ISSUE TITLE
Pandas 0.22.0 `DeprecationWarning` from `util.py:652`

### ISSUE THREAD

**Issue by macks22** [pydata/patsy#122]
The warning basically says it all:
```
/Users/<user>/anaconda2/envs/py3k/lib/python3.6/site-packages/patsy/util.py:652: DeprecationWarning: pandas.core.common.is_categorical_dtype is deprecated. import from the public API: pandas.api.types.is_categorical_dtype instead
  return safe_is_pandas_categorical_dtype(data.dtype)
```
Would be good to switch over to the new API soon to get rid of the warning and prevent breakage with future `pandas` versions.

**Comment by njsmith** [comment]
What version of patsy are you seeing this on?

**Comment by njsmith** [comment]
0.5.0 was released a few months ago, and I think upgrading will fix this :-)

**Comment by macks22** [comment]
That did it, thanks!
