### ISSUE TITLE
patsy folder licenses

### ISSUE THREAD

**Issue by Silviu-Caprar** [pydata/patsy#124]
Hello,

Regarding patsy 0.4.1:

Can you please specify if all files with Copyright Nathaniel Smith are under Python 2 ? 
In LICENSE.txt is mentioned only the module python.compat which I presume refers to python/compat.py

Can you please specify which license applies on mgcv_cubic_splines.py ?
Since this file is the only one where other copyright than Nathaniel Smith appears, what license refers to is not clear.
Is it the BSD 2 Clause or Python 2 ?

Thanks,
Silviu

**Comment by njsmith** [comment]
None of the code that's copyright Nathaniel Smith is under the Python 2 license.

Most of the code, as well as the overall package, is BSD 2 clause (in particular this includes all the code that's copyright Nathaniel Smith, and also the code in `mgcv_cubic_splines.py`).

It looks like at this point the only exception is the file `patsy/compat_ordereddict.py`, which is under the Python license. (IIRC there used to be some in `patsy/compat.py`, but it was since removed.)

**Comment by Silviu-Caprar** [comment]
In patsy/compat_ordereddict.py is mentioned that MIT License applies. Actually Python 2 applies ?

**Comment by njsmith** [comment]
Oh, I see, right I got confused – it looks like that file is MIT licensed like it says, and I guess we don't have any Python-licensed code anymore. (The code in that file also appears in Python itself under the Python license, but we got it from its original author via a different source where he also released it under an MIT license. I think.)

**Comment by Silviu-Caprar** [comment]
In /patsy/compat.py we have the following information: "Copied unchanged from Python 2.7.3's re.py module."
From License.txt it looks that the above file is licensed under Python 2.0. but in re.py file it looks like CNRI Python license applies (https://github.com/enthought/Python-2.7.3/blob/master/Lib/re.py). Does CNRI Python license actually applies on this file ?

**Comment by njsmith** [comment]
Oh, sorry, I was looking at current master, where that code's been deleted. From looking at Python's LICENSE file, my impression was that all of Python was relicensed from CNRI to the PSF license 2, so the license header in `re.py` is out of date. But that's a question for the Python folks, not for me :-).

**Comment by matthewwardrop** [comment]
Looks like this is solved, closing out.
