### ISSUE TITLE
Mixed effects formulas

### ISSUE THREAD

**Issue by andportnoy** [pydata/patsy#130]
Dear Nathaniel,

What do you think it would take to implement support for mixed effects formulas (parsing and design matrix construction) as they are used in R's `lme4`? In terms of effort, does it appear to you like it could be easily achieved by composing/reusing existing `patsy` features, or is it way more involved?

**Comment by njsmith** [comment]
When I wrote patsy this was one of the possible uses I had in mind, so the internals have the machinery you need. However, it's not currently exposed in a way that you can use from outside the library, so making that possible would need some thought and familiarity with the internals.

The basic flow for converting a formula to a design matrix is:

1. We parse the formula string, producing a parse tree (`patsy.parse_formula.parse_formula` – this is a private API)
2. We run an evaluator over the parse tree, producing a `ModelDesc` object (`patsy.desc.Evaluator` – this is also a private API). `ModelDesc` is public, and the public API that coordinates these two steps is `ModelDesc.from_factor`.
3. The `ModelDesc` is passed into the design matrix building machinery.

To support lme4 formulas, you'd need the parser to know about how to parse the new `|` operator, and then somehow during the evaluation stage you'd need to extract the information about the fixed and random effects. IIRC the fixed effects – everything that's not part of a `|` expression – are basically handled like any other formula (so in patsy you'd represent them as a `ModelDesc`), and then for each `|` you'd have one `ModelDesc` to represent the random effects, plus some kind of representation of the factors that they're conditioned on.

The parser itself is extensible: `patsy.parse_formula.parse_formula` even takes an `extra_operators=` argument. The evaluator is also extensible – see `Evaluator.add_op`. But, neither of these APIs have ever actually been used for anything – they were added as part of some vague plan to eventually support lme4-style formulas, that never got followed up on.

So... it's not trivial, but it is possible.

**Comment by andportnoy** [comment]
I see, thank you for the explanation, that kind of gives me hope. I'm considering investing some time in this so it could be used for `MixedLM` in `statsmodels`. The current interface there is much clunkier that `lme4`-style formulas.

**Comment by JackCaster** [comment]
> I see, thank you for the explanation, that kind of gives me hope. I'm considering investing some time in this so it could be used for `MixedLM` in `statsmodels`. The current interface there is much clunkier than `lme4`-style formulas.

@andportnoy Any news on this? I would love for Patsy to handle random effects!

**Comment by andportnoy** [comment]
@JackCaster I started working on this over the break, nothing that I would put up on GitHub yet. It will most likely live as a fork that updates from upstream until and if Nathaniel decides it belongs in patsy.

**Comment by andportnoy** [comment]
@JackCaster Here is a mixed effects library that supports R-style mixed effects formulas without using Patsy: https://github.com/stitchfix/diamond/blob/f8a309c7ad4d0d4651648c1a2b61a3f990825add/diamond/glms/glm.py#L224-L262

**Comment by JackCaster** [comment]
> @JackCaster Here is a mixed effects library that supports R-style mixed effects formulas without using Patsy: https://github.com/stitchfix/diamond/blob/f8a309c7ad4d0d4651648c1a2b61a3f990825add/diamond/glms/glm.py#L224-L262

Ok, cool. Thank you for the link. 
I uploaded a [gist](https://gist.github.com/JackCaster/f9194bfdf9b7c45ed69deab3b0e09fe5) to describe how one could compute the design matrices X (fixed effects) and Z (random effects), using the current functionalities of Patsy. May be useful to someone that will stumble upon this issue.

**Comment by andportnoy** [comment]
Thank you, will take a look!

**Comment by twiecki** [comment]
This would be an amazing feature, especially for pymc3. Any progress?

**Comment by andportnoy** [comment]
@twiecki @njsmith @JackCaster Happy to say I've made some progress since. I am working on a package to support mixed effects model fitting in Python, using lme4-style formulas.

So far, the frontend which constructs the model matrices is practically complete, it uses patsy to generate the X and the Z. I am now working on generation of the relative covariance factor and a set of tests to verify correctness against lme4 in R.

This very simple Python module can be found here: https://github.com/andportnoy/mixed.

**Comment by andportnoy** [comment]
It also appears that parsing of lme4-style formulas has been implemented without relying on Patsy in this package (which as you can see references this issue above): https://github.com/pyro-ppl/brmp/blob/master/brmp/formula.py

**Comment by twiecki** [comment]
@andportnoy That is quite interesting, do you plan to do a PR to patsy or fork it? I think ideally they'd both be part of the same repo.

**Comment by andportnoy** [comment]
@twiecki I agree, although more work is needed to make this usable. For instance, dense representation of this Z matrix makes it impractical for fitting any "real world" model, since the Z is almost always highly sparse and at the same time larger than the X.

I also don't know if @njsmith thinks this would belong in Patsy at all.

But a PR probably won't hurt.

**Comment by twiecki** [comment]
I have the sneaking suspicion that Patsy is probably not actively maintained at this point. @njsmith please let me know if that is false, if it isn't, are you fine with giving write access to the repo to me and/or @andportnoy?

**Comment by twiecki** [comment]
@andportnoy Checking in if you're still interested in doing a PR?

**Comment by andportnoy** [comment]
@twiecki Still interested.

**Comment by twiecki** [comment]
Since @njsmith is MIA I wonder if it might be best to fork the project. What do you think @andportnoy?

**Comment by andportnoy** [comment]
@twiecki I don’t think he’s totally MIA: he pushed a commit just a few days ago: https://github.com/python-trio/trio/commits?author=njsmith&since=2020-03-01&until=2020-03-06.
Maybe we just need to ping him elsewhere or wait for him to read through his GitHub notifications. His temporary absence isn’t blocking anything, so I’d rather wait than fork the project.

@njsmith Please let me know if you are interested in a PR implementing mixed effects formula parsing + matrix construction.

**Comment by andportnoy** [comment]
@twiecki Emailed Nathaniel, let’s wait for a bit.

**Comment by tomicapretto** [comment]
In [Bambi](https://github.com/bambinos/bambi) we started to work in our own implementation that also works for random effects. The library is still a work in progress but the majority of the work is done, have a look [here](https://github.com/bambinos/formulae) if you want.

**Comment by tomicapretto** [comment]
Hi all,

Patsy is not going to be actively maintained anymore, so this feature is not going to be possible in Patsy. 

However, you have can use [formulae](https://github.com/bambinos/formulae) if you want to use mixed-effects formulas right now.
