### ISSUE TITLE
No name 'dmatrices' in module 'patsy'

### ISSUE THREAD

**Issue by ghaisanyukta** [pydata/patsy#147]
Getting this error ->
No name 'dmatrices' in module 'patsy'

while running this line ->
from patsy import dmatrices

Any idea how to resolve it?

**Comment by r-barnes** [comment]
I do not get this error with Patsy 0.5.1. Which version are you using?

**Comment by IanQS** [comment]
I know this is REALLY old at this point but I solved this by doing `from patsy.highlevel import dmatrices`.

LMK if this helps!

**Comment by matthewwardrop** [comment]
I cannot reproduce this, and the code looks sound. Feel free to reopen if this happens again.
