### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by Julian** [pydata/patsy#154]
Hi! Thanks for patsy.

Any chance a release could be pushed out?

Specifically one for the current HEAD, containing #140, would be great, it's still emitting warnings (on 3.8).

**Comment by jaimergp** [comment]
We'd also need this for https://github.com/choderalab/pymbar/issues/351. Thank you!

**Comment by HippocampusGirl** [comment]
Any update on this?

**Comment by CamKirk** [comment]
@njsmith any way we can help push to the next release?

**Comment by matthewwardrop** [comment]
I've pushed out 0.5.2, and renovated the CI tooling. As indicated in the readme, we're dedicated to keeping `patsy` kicking along indefinitely, while pushing new innovations to formulaic.

**Comment by CamKirk** [comment]
Thanks @matthewwardrop and team!

**Comment by tomicapretto** [comment]
Thanks for the work @matthewwardrop
