### ISSUE TITLE
MAINT: Reorder imports to avoid deprecation warning importing Mapping from collections.

### ISSUE THREAD

**Issue by jeroenbouwman** [pydata/patsy#165]
Line 13 (from collections import Mapping) in  constraint.py gives the following warning for python versions > 3.3:

DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working

A change on line 13 in constraint.py from:

from collections import Mapping

to:

from collections.abc import Mapping

should fix this and makes sure that patsy also works with python 3.9

**Comment by bashtage** [comment]
This is already handeled with a try except.  

https://github.com/pydata/patsy/blob/4c613d0ad3009044ca3aee5a5d70bd56af8f396b/patsy/constraint.py#L12-L16

**Comment by dengf** [comment]
Hi, I Bashtage-

I noticed that the released 0.5.1 version contraint.py does not include the try except while it is included in the master branch.

**Comment by bashtage** [comment]
statsmodels tests on Python 3.9 against patsy 0.5.1. It seems to work find so I don't see any needs for a rush to change anything.

https://dev.azure.com/statsmodels/statsmodels-testing/_build/results?buildId=3033&view=logs&j=3f9beef4-2a87-5b9a-d136-eeaf4b842580&t=d7fee839-a503-5b05-b0a4-5008c56e73a3

**Comment by ns-admetrics** [comment]
It's a bit unfortunate to say one sees no need for a rush to fix an issue that has been around since Python 3.3, in a project that hasn't seen a release in over two years.

All you'd seem to need to do here is to release an 0.5.2 with the fix (which already exists), no?

**Comment by Samreay** [comment]
Given the fix is already on master, is it possible to make a release as suggested? Even if it runs at the moment, patsy does cause deprecation warnings to be logged in projects which have it as a dependency.

**Comment by bashtage** [comment]
As far as I know on @njsmith can post a new release to PyPI.

**Comment by danschef** [comment]
Any chance to get a new release soon?

**Comment by ivirshup** [comment]
Since the warning is now:

```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
```

And 3.10 is out in beta, it would be really good if this could get updated soon so downstream packages can work in python 3.10. If @njsmith isn't available, could someone from the pydata organization step in and make a release?

**Comment by jkklapp** [comment]
Bump

**Comment by Nieju** [comment]
Please fix!

**Comment by Seninus** [comment]
It seems nobody is maintaining this package?  the latest release is from 2018....   this error is impacting all the downstream packages.....

**Comment by matthewwardrop** [comment]
Greetings!

A month or so ago I inherited the maintenance of this package, which is now feature frozen as I wrap up the mostly feature-complete replacement [Formulaic](https://github.com/matthewwardrop/formulaic), of which I am also the maintainer. My plan is to fix issues like these ones so that users who are content with patsy can continue to rely upon it. I'll patch this soon.

**Comment by matthewwardrop** [comment]
Okay... I've pushed out 0.5.2 with this small change, and cleaned up the CI testing.
