### ISSUE TITLE
Deprcation warning for import from collections

### ISSUE THREAD

**Issue by prakharmody1996** [pydata/patsy#167]
/mnt/.../venv/lib/python3.8/site-packages/patsy/constraint.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working

**Comment by tirkarthi** [comment]
Seems like a duplicate of https://github.com/pydata/patsy/issues/165

**Comment by bashtage** [comment]
Closing as dupe.
