### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [pydata/patsy#172]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine patsy/state.py, patsy/util.py and observe `heterogenous`, however expect to see `heterogeneous`.
- Examine patsy/splines.py and observe `specificed`, however expect to see `specified`.
- Examine doc/expert-model-specification.rst and observe `represention`, however expect to see `representation`.
- Examine doc/quickstart.rst and observe `concatentation`, however expect to see `concatenation`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/patsy/pull/new/bugfix_typos

Thanks.

**Comment by matthewwardrop** [comment]
Thanks Tim.
