### ISSUE TITLE
pytest dependency issue

### ISSUE THREAD

**Issue by gospodima** [pydata/patsy#215]
Hello,

I just saw CI pipeline of my project failed due to new 1.0.0 release. Looks like in #214 pytest import was added in [`patsy/eval.py`](https://github.com/pydata/patsy/blob/a514e0c259b062694a5645071634dd3cee337ceb/patsy/eval.py#L21). Since pytest is an optional requirement for tests, it results with `ModuleNotFoundError: No module named 'pytest'` in case patsy was installed without test dependencies.

**Comment by bashtage** [comment]
Thanks for reporting it to us. We'll need to do a point release very quickly.

**Comment by elongl** [comment]
Hi, this is breaking us as well.

**Comment by tdekelver-bd** [comment]
This also causes issue with statsmodels package that has patsy as depencency.

**Comment by bashtage** [comment]
Patch in master.  Leaving this open until 1.0.1.  @matthewwardrop would be great if you could post a release when you have a chance.

**Comment by bashtage** [comment]
Release 1.0.1 is now on PyPI.

**Comment by bguillod** [comment]
Is this going to be released to conda and conda-forge soon as well?

**Comment by matthewwardrop** [comment]
Ugh... Apologies folks. And thanks @bashtage .

**Comment by matthewwardrop** [comment]
I have yanked the 1.0.0 release from PyPI, submitted a [broken PR request](https://github.com/conda-forge/admin-requests/pull/1161) to conda-forge to prevent continued use of the patsy 1.0.0 package, and expedited the release of 1.0.1 into conda [PR](https://github.com/conda-forge/patsy-feedstock/pull/18).

I suppose the lesson here is not to publish packages late at night, especially for code-bases which you have grown only distantly familiar. Thanks again @bashtage for the quick fix.

**Comment by bashtage** [comment]
I would worry too much about it. I think the very out-of-date style that patsy uses where tests are integrated into the main package is probably more at fault than letting this one slip through.

**Comment by bollwyvl** [comment]
Thanks for the quick response and thinking of us poor schlubs over on CF. 

A quick CI win is a "clean room" job that downloads the whl/sdist and installs it...

```bash
pip install --find-links=dist --no-index-url patsy
pip check
python -c "import patsy"
```

**Comment by matthewwardrop** [comment]
@bollwyvl Yeah... @bashtage added a check [here](https://github.com/pydata/patsy/pull/216/files) that should test that things work sans pytest; but a clean-room install at the end of the CI job is a nice generic solution. Thanks for your quick conda-forge responses, btw.

Of course, this project is heading the way of the dodo just as soon as I can find some time to port statsmodels and a few other projects onto formulaic.
