### ISSUE TITLE
Rude install behavior

### ISSUE THREAD

**Issue by rgommers** [pydata/patsy#5]
Hi Nathaniel, can you please remove this line 

    install_requires=["numpy"],

from setup.py? It isn't a good idea to have this line here, because then if you use pip or easy_install to install patsy, it will try to upgrade numpy under some circumstances. This is rude and should never happen automatically. In my case, I had 1.8.0-dev on my system (in-place build) and pip tried to ignore it and install 1.7.0 into site-packages.

The same was done for statsmodels. There it was replaced with

     try:
         from numpy.version import short_version as npversion
     except ImportError:
         raise ImportError("statsmodels requires numpy")

**Comment by rgommers** [comment]
@njsmith you still didn't close this issue as invalid:)

**Comment by njsmith** [comment]
Well, it wasn't exactly resolved :-). But I guess things are looking up enough these days that we can move on...
