### ISSUE TITLE
Idiom question for dataframes + test data

### ISSUE THREAD

**Issue by kyleabeauchamp** [pydata/patsy#51]
I have a workflow where I want to construct a design matrix from some training data that happens to be stored in a pandas dataframe.  I then want to be able to take a *new* pandas dataframe and apply the same transformation, so that I can have a pure numpy representation of test dataset with the same category indices.  I suppose an error would be raised if my training dataset has categorical values that were missing in the original dmatrix.  

I can't seem to figure out the most idiomatic way to achieve this.  

My big picture workflow looks something like this:

1.  X = dmatrix("y ~ v0 * v1", train_data, return_type="dataframe")
2.  X_sparse = scipy.sparse.csr_matrix(X.values)
3.  fit a custom model (using pymc2, actually) with the sparse representation of the data
4.  X_test = X.transform_into_basis(test_data)
5.  X_test_sparse = scipy.sparse.csr_matrix(X_test.values)
6.  X_test = model.predict(X_test_sparse)

What I need is a clean way to transform / featurize my test dataset.  I suppose I'd also love for the API to look something like the sklearn `model.transform()` api.

Does this exist?  Can someone point me in the right direction?

**Comment by njsmith** [comment]
Does this work?

X_test = dmatrix(X.design_info.builder, test_data, return_type="dataframe")

(X.design_info.builder is a DesignMatrixBuilder, which is a mostly-opaque
class which encapsulates all the decisions that patsy made while reading
your original data -- what levels of categorical data you have, which order
the columns go in, etc. etc. dmatrix and friends are basically a thin
wrapper around design_matrix_builders and build_design_matrices -- see
http://patsy.readthedocs.org/en/latest/API-reference.html#patsy.design_matrix_builders
if you're curious about the details.)

On Sun, Jan 11, 2015 at 8:57 PM, Kyle Beauchamp <notifications@github.com>
wrote:

> I have a workflow where I want to construct a design matrix from some
> training data that happens to be stored in a pandas dataframe. I then want
> to be able to take a *new* pandas dataframe and apply the same
> transformation, so that I can have a pure numpy representation of test
> dataset with the same category indices. I suppose an error would be raised
> if my training dataset has categorical values that were missing in the
> original dmatrix.
>
> I can't seem to figure out the most idiomatic way to achieve this.
>
> My big picture workflow looks something like this:
>
>    1. X = dmatrix("y ~ v0 * v1", train_data, return_type="dataframe")
>    2. X_sparse = scipy.sparse.csr_matrix(X.values)
>    3. fit a custom model (using pymc2, actually) with the sparse
>    representation of the data
>    4. X_test = X.transform_into_basis(test_data)
>    5. X_test_sparse = scipy.sparse.csr_matrix(X_test.values)
>    6. X_test = model.predict(X_test_sparse)
>
> What I need is a clean way to transform / featurize my test dataset. I
> suppose I'd also love for the API to look something like the sklearn
> model.transform() api.
>
> Does this exist? Can someone point me in the right direction?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydata/patsy/issues/51>.
>



-- 
Nathaniel J. Smith
Postdoctoral researcher - Informatics - University of Edinburgh
http://vorpus.org

**Comment by kyleabeauchamp** [comment]
I think this does the trick.
