### ISSUE TITLE
Malfunctionary testing in categorical.py

### ISSUE THREAD

**Issue by PashaPodolsky** [pydata/patsy#58]
Have no idea what is testing in
        cat = pandas.Categorical([1, 0, -1], ("a", "b"))
        conv = categorical_to_int(cat, ("a", "b"), NAAction())
        assert np.all(conv == [1, 0, -1])
of test_categorical_to_int(). Need to be corrected

**Comment by JanSchulz** [comment]
This looks like it should be converted to `pandas.Categorical.from_codes([1, 0, -1], ("a", "b"))`. It should also make sure that this is only tested on pandas >0.15, as this method (and the change from `codes and categories` to the `values and categories` version of the "two arrays constructor").

http://pandas.pydata.org/pandas-docs/dev/categorical.html#old-style-constructor-usage
http://pandas.pydata.org/pandas-docs/dev/generated/pandas.core.categorical.Categorical.from_codes.html

**Comment by JanSchulz** [comment]
This line should also change: https://github.com/pydata/patsy/blob/master/patsy/categorical.py#L290
`Categorical.levels` is deprecated and should become `Categorical.categories`

**Comment by JanSchulz** [comment]
Oups, I think I was there already: https://github.com/pydata/patsy/pull/47/files

**Comment by njsmith** [comment]
I think this issue is defunct now that we have proper support for pandas 0.15+'s categoricals? Please re-open if not.
