### ISSUE TITLE
dmatrices: fix "ValueError: For numerical factors, num_columns must be an int"

### ISSUE THREAD

**Issue by patrick-nicholson** [pydata/patsy#73]
With an interaction term, dmatrices is failing with the error `ValueError: For numerical factors, num_columns must be an int`.  

The tests `if not isinstance(num_columns, int)` in the `design_info` module (lines 87 and 218) return `True` because `num_columns` is a `long` rather than an `int`.  

Changing the test to `if not isinstance(num_columns, (int, long))` has worked for me.

**Comment by jewellthomas** [comment]
I think this was resolved in v0.4.1.
