### ISSUE TITLE
Python. Titanic Data Error

### ISSUE THREAD

**Issue by pintolx** [pydata/patsy#78]
I am trying out some machine learning algorithms to be able to predict the people who survived who were aboard the titanic. I am following this example https://github.com/mlakhavani/titanic/blob/master/TitanixFinal.ipynb

However on from patsy import dmatrices
```
y, x = dmatrices('survived ~ sex + age + sibsp + parch + pclass + fare + C + Q + S + Col + Dr + Master + Miss + Mr + Mrs + Rev',
                 titanic_train, return_type="dataframe")

y_test, x_test = dmatrices('survived ~ sex + age + sibsp + parch + pclass + fare + + C + Q + S + Col + Dr + Master + Miss + Mr + Mrs + Rev',
                           titanic_test, return_type="dataframe")
i get this error
PatsyError                                Traceback (most recent call last)
<ipython-input-153-63b2f538454b> in <module>()
      1 y_test, x_test = dmatrices('Survived ~ Sex + Age + SibSp + Parch + Pclass + Fare + + C + Q + S ++ Dr + Master + Miss + Mr + Mrs + Rev',
----> 2                            titanic_test, return_type="dataframe")

C:\Anaconda\lib\site-packages\patsy\highlevel.pyc in dmatrices(formula_like, data, eval_env, NA_action, return_type)
    295     eval_env = EvalEnvironment.capture(eval_env, reference=1)
    296     (lhs, rhs) = _do_highlevel_design(formula_like, data, eval_env,
--> 297                                       NA_action, return_type)
    298     if lhs.shape[1] == 0:
    299         raise PatsyError("model is missing required outcome variables")

C:\Anaconda\lib\site-packages\patsy\highlevel.pyc in _do_highlevel_design(formula_like, data, eval_env, NA_action, return_type)
    154         return build_design_matrices(builders, data,
    155                                      NA_action=NA_action,
--> 156                                      return_type=return_type)
    157     else:
    158         # No builders, but maybe we can still get matrices

C:\Anaconda\lib\site-packages\patsy\build.pyc in build_design_matrices(builders, data, NA_action, return_type, dtype)
    945         for evaluator in builder._evaluators:
    946             if evaluator not in evaluator_to_values:
--> 947                 value, is_NA = evaluator.eval(data, NA_action)
    948                 evaluator_to_isNAs[evaluator] = is_NA
    949                 # value may now be a Series, DataFrame, or ndarray

C:\Anaconda\lib\site-packages\patsy\build.pyc in eval(self, data, NA_action)
    161         result = self.factor.eval(self._state, data)
    162         result = categorical_to_int(result, self._levels, NA_action,
--> 163                                     origin=self.factor)
    164         assert result.ndim == 1
    165         return result, np.asarray(result == -1)

C:\Anaconda\lib\site-packages\patsy\categorical.pyc in categorical_to_int(data, levels, NA_action, origin)
    270     if hasattr(data, "shape") and len(data.shape) > 1:
    271         raise PatsyError("categorical data must be 1-dimensional",
--> 272                          origin)
    273     if (not iterable(data)
    274         or isinstance(data, (six.text_type, six.binary_type))):

PatsyError: categorical data must be 1-dimensional
    Survived ~ Sex + Age + SibSp + Parch + Pclass + Fare + + C + Q + S ++ Dr + Master + Miss + Mr + Mrs + Rev

```
How can i solve this issue?

**Comment by njsmith** [comment]
The error message is saying that you've managed to make one of your variable contain multiple columns, while it's being detected as categorical (meaning it has string or boolean or categorical or maybe object dtype).

The very last line of the error message, which you didn't paste, should have some carets indicating which variable was problematic. E.g. it might look like
```
Survived ~ Sex + Age + SibSp + Parch + Pclass + Fare
                 ^^^
```
where the ^^^ are indicating that the Age variable is causing the problem.

In general the code you linked to is spending a while lot of time doing stuff that normally you would have patsy do for you, and I'm not sure how correct it is or how you modified it, so I'm afraid I can't really help any more than that based on what you've said so far. I'd check to see which variable it is and then look at that variable and see if its shape and dtype are what they should be.

**Comment by pintolx** [comment]
Yes, the Issue you pointed out is correct, the challenge is that the variable its pointing to is an integer, and not categorical

**Comment by njsmith** [comment]
How do you know that? Can you paste what you see?

**Comment by pintolx** [comment]
@njsmith  Survived  Sex  Pclass  Parch  Age  SibSp  Parch      Fare  C  Q  S  Dr  0           1    0       3      0   22      1      0    7.2500  0  0  1   0   
1           2    1       1      1   38      1      0   71.2833  1  0  0   0   
2           3    1       3      1   26      0      0    7.9250  0  0  1   0   
3           4    1       1      1   35      1      0   53.1000  0  0  1   0   
4           5    0       3      0   35      0      0    8.0500  0  0  1   0   
5           6    0       3      0   28      0      0    8.4583  0  1  0   0   
6           7    0       1      0   54      0      0   51.8625  0  0  1   0   
7           8    0       3      0    2      3      1   21.0750  0  0  1   0   
8           9    1       3      1   27      0      2   11.1333  0  0  1   0   
9          10    1       2      1   14      1      0   30.0708  1  0  0   0   
10         11    1       3      1    4      1      1   16.7000  0  0  1   0   
11         12    1       1      1   58      0      0   26.5500  0  0  1   0   
12         13    0       3      0   20      0      0    8.0500  0  0  1   0   
13         14    0       3      0   39      1      5   31.2750  0  0  1   0   
14         15    0       3      1   14      0      0    7.8542  0  0  1   0   
15         16    1       2      1   55      0      0   16.0000  0  0  1   0   
16         17    0       3      0    2      4      1   29.1250  0  1  0   0   
17         18    1       2      0   28      0      0   13.0000  0  0  1   0   
18         19    0       3      1   31      1      0   18.0000  0  0  1   0   
19         20    1       3      1   28      0      0    7.2250  1  0  0   0   
20         21    0       2      0   35      0      0   26.0000  0  0  1   0   
21         22    1       2      0   34      0      0   13.0000  0  0  1   0   
22         23    1       3      1   15      0      0    8.0292  0  1  0   0   
23         24    1       1      0   28      0      0   35.5000  0  0  1   0   
24         25    0       3      1    8      3      1   21.0750  0  0  1   0   
25         26    1       3      1   38      1      5   31.3875  0  0  1   0   
26         27    0       3      0   28      0      0    7.2250  1  0  0   0   
27         28    0       1      0   19      3      2  263.0000  0  0  1   0   
28         29    1       3      1   28      0      0    7.8792  0  1  0   0   
29         30    0       3      0   28      0      0    7.8958  0  0  1   0   
..        ...  ...     ...    ...  ...    ...    ...       ... .. .. ..  ..   
861       862    0       2      0   21      1      0   11.5000  0  0  1   0   
862       863    1       1      1   48      0      0   25.9292  0  0  1   0   
863       864    0       3      1   28      8      2   69.5500  0  0  1   0   
864       865    0       2      0   24      0      0   13.0000  0  0  1   0   
865       866    1       2      1   42      0      0   13.0000  0  0  1   0   
866       867    1       2      1   27      1      0   13.8583  1  0  0   0   
867       868    0       1      0   31      0      0   50.4958  0  0  1   0   
868       869    0       3      0   28      0      0    9.5000  0  0  1   0   
869       870    1       3      0    4      1      1   11.1333  0  0  1   0   
870       871    0       3      0   26      0      0    7.8958  0  0  1   0   
871       872    1       1      1   47      1      1   52.5542  0  0  1   0   
872       873    0       1      0   33      0      0    5.0000  0  0  1   0   
873       874    0       3      0   47      0      0    9.0000  0  0  1   0   
874       875    1       2      1   28      1      0   24.0000  1  0  0   0   
875       876    1       3      1   15      0      0    7.2250  1  0  0   0   
876       877    0       3      0   20      0      0    9.8458  0  0  1   0   
877       878    0       3      0   19      0      0    7.8958  0  0  1   0   
878       879    0       3      0   28      0      0    7.8958  0  0  1   0   
879       880    1       1      1   56      0      1   83.1583  1  0  0   0   
880       881    1       2      1   25      0      1   26.0000  0  0  1   0   
881       882    0       3      0   33      0      0    7.8958  0  0  1   0   
882       883    0       3      1   22      0      0   10.5167  0  0  1   0   
883       884    0       2      0   28      0      0   10.5000  0  0  1   0   
884       885    0       3      0   25      0      0    7.0500  0  0  1   0   
885       886    0       3      1   39      0      5   29.1250  0  1  0   0   
886       887    0       2      0   27      0      0   13.0000  0  0  1   0   
887       888    1       1      1   19      0      0   30.0000  0  0  1   0   
888       889    0       3      1   28      1      2   23.4500  0  0  1   0   
889       890    1       1      0   26      0      0   30.0000  1  0  0   0   
890       891    0       3      0   32      0      0    7.7500  0  1  0   0   

     Master  Miss  Mr  Mrs  Rev  
0         0     0   1    0    0  
1         0     0   0    1    0  
2         0     1   0    0    0  
3         0     0   0    1    0  
4         0     0   1    0    0  
5         0     0   1    0    0  
6         0     0   1    0    0  
7         1     0   0    0    0  
8         0     0   0    1    0  
9         0     0   0    1    0  
10        0     1   0    0    0  
11        0     1   0    0    0  
12        0     0   1    0    0  
13        0     0   1    0    0  
14        0     1   0    0    0  
15        0     0   0    1    0  
16        1     0   0    0    0  
17        0     0   1    0    0  
18        0     0   0    1    0  
19        0     0   0    1    0  
20        0     0   1    0    0  
21        0     0   1    0    0  
22        0     1   0    0    0  
23        0     0   1    0    0  
24        0     1   0    0    0  
25        0     0   0    1    0  
26        0     0   1    0    0  
27        0     0   1    0    0  
28        0     1   0    0    0  
29        0     0   1    0    0  
..      ...   ...  ..  ...  ...  
861       0     0   1    0    0  
862       0     0   0    1    0  
863       0     1   0    0    0  
864       0     0   1    0    0  
865       0     0   0    1    0  
866       0     1   0    0    0  
867       0     0   1    0    0  
868       0     0   1    0    0  
869       1     0   0    0    0  
870       0     0   1    0    0  
871       0     0   0    1    0  
872       0     0   1    0    0  
873       0     0   1    0    0  
874       0     0   0    1    0  
875       0     1   0    0    0  
876       0     0   1    0    0  
877       0     0   1    0    0  
878       0     0   1    0    0  
879       0     0   0    1    0  
880       0     0   0    1    0  
881       0     0   1    0    0  
882       0     1   0    0    0  
883       0     0   1    0    0  
884       0     0   1    0    0  
885       0     0   0    1    0  
886       0     0   0    0    1  
887       0     1   0    0    0  
888       0     1   0    0    0  
889       0     0   1    0    0  
890       0     0   1    0    0

**Comment by njsmith** [comment]
Which variable is causing the problem?

**Comment by pintolx** [comment]
PatsyError: categorical data must be 1-dimensional
    Survived ~ Sex + Age + SibSp + Parch + Pclass + Fare + + C + Q + S ++ Dr + Master + Miss + Mr + Mrs + Rev
                                   ^^^^^

**Comment by pintolx** [comment]
Rev is causing the problems

**Comment by njsmith** [comment]
(I edited your comment to add triple-backticks around the pasted text, so github would show it as fixed width code.)

You posted two comments 30 seconds apart; one of them says that Parch is causing the problem and one says that Rev is causing the problem :-). Which is it?

What does `titanic_test["Parch"]` print? How about `titanic_test["Parch"].dtype` and `titanic_test["Parch"].shape`?

**Comment by pintolx** [comment]
print titanic_test['Parch'].shape
(401, 2)
print titanic_test['Parch']
     Parch  Parch
779      1      1
367      1      0
98       1      1
698      0      1
97       0      1
220      0      0
249      0      0
147      1      2
108      0      0
691      1      1
751      0      1
49       1      0
106      1      0
462      0      0
378      0      0
879      1      1
882      1      0
101      0      0
210      0      0
73       0      0
121      0      0
558      1      1
858      1      3
811      0      0
663      0      0
872      0      0
415      1      0
545      0      0
686      0      1
246      1      0
..     ...    ...
336      0      0
867      0      0
611      0      0
766      0      0
85       1      0
82       1      0
323      1      1
338      0      0
433      0      0
266      0      1
522      0      0
81       0      0
2        1      0
742      1      2
774      1      3
63       0      2
202      0      0
628      0      0
329      1      1
32       1      0
679      0      1
460      0      0
755      0      1
214      0      0
531      0      0
68       1      2
863      1      2
723      0      0
687      0      0
571      1      0
 print titanic_test['Parch'].dtype
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-162-5685ad4b3663> in <module>()
----> 1 print titanic_test['Parch'].dtype

C:\Anaconda\lib\site-packages\pandas\core\generic.pyc in __getattr__(self, name)
   1841                 return self[name]
   1842             raise AttributeError("'%s' object has no attribute '%s'" %
-> 1843                                  (type(self).__name__, name))
   1844 
   1845     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'dtype'

**Comment by njsmith** [comment]
Huh. Well, that tells us that whatever you've done, it's very different than anything in that notebook you linked to. And if you're only getting this on the test set and not the training set, then it probably means you made some mistake in your code above setting up the test set.

If you do `titanic_test["Patch"].dtypes` then I bet it will say that one of those columns has type `object`, which means that you created it in a way that you said it can contain arbitrary non-integer values (like strings or whatever), so patsy is taking you at your word and treating it as categorical even though all the values happen to be numbers. So you need to figure out how to fix that. (Maybe it shouldn't be a dataframe with two columns, either.)

Figuring out how happened and fixing it will require looking at your code that created this object, and that's more a general pandas question. If you can't figure it out then I'd suggest asking on stackoverflow or the pandas mailing list.

**Comment by njsmith** [comment]
Not sure there's anything else i can do to help, and it doesn't look like there's any patsy bug here, so closing. Feel free to reopen if that's incorrect.

**Comment by pintolx** [comment]
Thanks @njsmith am going through the code again, will revert when i find the error
