### ISSUE TITLE
bug: patsy fails when included in standalone applications

### ISSUE THREAD

**Issue by pbrod** [pydata/patsy#99]
When I include patsy in a standalone application made by cx_freeze I get a type exceptions error message:

<type 'exceptions.TypeError'>: expected string or buffer'

The reason for this error is that python sets all docstrings to None when compiling the source code.
In order to fix this all lines manipulating the __doc__ should test for the cornercase that it is None.

The two lines in patsy/mgcv_cubic_splines.py which say:

       __doc__ = __doc__ + CubicRegressionSpline.commondoc

should therefore be replaced with

       __doc__ = __doc__ + CubicRegressionSpline.commondoc if __doc__ else CubicRegressionSpline.commondoc

**Comment by pbrod** [comment]
Not a issue anymore

**Comment by njsmith** [comment]
Yeah, this is a dupe of #52, fixed in 4a4543be6cb6f675f08dbe01483199a3e3484087, released in v0.4.0
